### ISSUE TITLE
Illegal bandwidth value: 57 on disabled Lora_std.bandwidth

### ISSUE THREAD

**Issue by brocaar** [lorabasics/basicstation#22]
Even when the LoRa Std channel is disabled, the Basic Station seems to validate the bandwidth of this channel:

```
         "chan_Lora_std": {
            "enable": false,
            "radio": 0,
            "if": 0,
            "bandwidth": 0,
            "spread_factor": 0
         },
```

Raises the following error:

```
2019-04-03 12:48:46.085 [TCE:VERB] Connecting to MUXS...
2019-04-03 12:48:46.103 [TCE:VERB] Connected to MUXS.
2019-04-03 12:48:46.134 [JSN:ERRO] @.chan_Lora_std.bandwidth: Illegal bandwidth value: 57 (must be 125000, 250000, or 500000)
2019-04-03 12:48:46.134 [RAL:ERRO] Parsing of JSON failed - 'router_config.sx1301_conf' ignored
2019-04-03 12:48:46.134 [any:ERRO] Closing connection to muxs - error in s2e_onMsg
```

This works fine:

```
         "chan_Lora_std": {
            "enable": false,
            "radio": 0,
            "if": 0
         },
```

Wouldn't it be better when `enable` is set to false to completely ignore the fields for this channel?

**Comment by beitler** [comment]
Station generally parses JSON strings in a streaming way, scanning each char just once. During parsing some first-stage validation is being done. Since we don't want to enforce a certain order within a JSON object, we have to parse and validate the bandwidth value in a context-free manner. Therefore, if you set a value, it better be valid. Alternatively, just drop the field, as you correctly identified. This is a small inconvenience but allows for efficient JSON parsing. Given that these JSON strings will generally be machine-generated, I don't think this inconvenience is hurting much.
